### ISSUE TITLE
AttributeError: 'SelectorModel' object has no attribute 'killed'

### ISSUE THREAD

**Issue by twlz0ne** [mooz/percol#69]
```sh
➜ ps aux | percol
Traceback (most recent call last):
  File "/usr/local/bin/percol", line 31, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/percol/cli.py", line 284, in main
    exit_code = percol.loop()
  File "/usr/local/lib/python2.7/site-packages/percol/__init__.py", line 180, in loop
    self.handle_key(self.screen.getch())
  File "/usr/local/lib/python2.7/site-packages/percol/__init__.py", line 248, in handle_key
    self.last_key = self.handle_normal_key(ch)
  File "/usr/local/lib/python2.7/site-packages/percol/__init__.py", line 264, in handle_normal_key
    self.keymap[k](self)
  File "~/.percol.d/rc.py", line 7, in <lambda>
    "C-y" : lambda percol: percol.command.yank(),
  File "/usr/local/lib/python2.7/site-packages/percol/command.py", line 219, in yank
    if self.model.killed:
AttributeError: 'SelectorModel' object has no attribute 'killed'
```

- OS X 10.9 & Python 2.7.7
- Ubuntu 12.04 &  Python 2.6.3
- Percol 0.1.0

**Comment by wu-nerd** [comment]
Same problem when press C-y
``` bash
Traceback (most recent call last):
  File "/usr/local/Cellar/percol/0.2.1/libexec/bin/percol", line 14, in <module>
    main()
  File "/usr/local/Cellar/percol/0.2.1/libexec/lib/python2.7/site-packages/percol/cli.py", line 267, in main
    exit_code = percol.loop()
  File "/usr/local/Cellar/percol/0.2.1/libexec/lib/python2.7/site-packages/percol/__init__.py", line 164, in loop
    self.handle_key(self.screen.getch())
  File "/usr/local/Cellar/percol/0.2.1/libexec/lib/python2.7/site-packages/percol/__init__.py", line 233, in handle_key
    self.last_key = self.handle_normal_key(ch)
  File "/usr/local/Cellar/percol/0.2.1/libexec/lib/python2.7/site-packages/percol/__init__.py", line 249, in handle_normal_key
    self.keymap[k](self)
  File "/Users/nerd/.percol.d/rc.py", line 8, in <lambda>
    "C-y" : lambda percol: percol.command.yank(),
  File "/usr/local/Cellar/percol/0.2.1/libexec/lib/python2.7/site-packages/percol/command.py", line 202, in yank
    if self.model.killed:
AttributeError: 'SelectorModel' object has no attribute 'killed'
```

rc.py:
``` python
percol.import_keymap({
    # "C-h" : lambda percol: percol.command.delete_backward_char(),
    # "C-d" : lambda percol: percol.command.delete_forward_char(),
    # "C-k" : lambda percol: percol.command.kill_end_of_line(),
     "C-y" : lambda percol: percol.command.yank(),
    # "C-t" : lambda percol: percol.command.transpose_chars(),
    # "C-a" : lambda percol: percol.command.beginning_of_line(),
    # "C-e" : lambda percol: percol.command.end_of_line(),
    # "C-b" : lambda percol: percol.command.backward_char(),
    # "C-f" : lambda percol: percol.command.forward_char(),
    # "M-f" : lambda percol: percol.command.forward_word(),
    # "M-b" : lambda percol: percol.command.backward_word(),
    # "M-d" : lambda percol: percol.command.delete_forward_word(),
    # "M-h" : lambda percol: percol.command.delete_backward_word(),
    # "C-n" : lambda percol: percol.command.select_next(),
    # "C-p" : lambda percol: percol.command.select_previous(),
    # "C-v" : lambda percol: percol.command.select_next_page(),
    # "M-v" : lambda percol: percol.command.select_previous_page(),
    # "M-<" : lambda percol: percol.command.select_top(),
    # "M->" : lambda percol: percol.command.select_bottom(),
    # "C-m" : lambda percol: percol.finish(),
    # "C-j" : lambda percol: percol.finish(),
    # "C-g" : lambda percol: percol.cancel(),
})
```


- macOS    10.13.6 (17G65)
- Python    2.7.15
- Percol 0.2.1
