### ISSUE TITLE
Error run on python3 0.1.0 release

### ISSUE THREAD

**Issue by Hubbitus** [mooz/percol#78]
It marked support python3, but apperently is not:
```
$ percol
Traceback (most recent call last):
  File "/bin/percol", line 31, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/percol/cli.py", line 225, in main
    tty_f.write(INSTRUCTION_TEXT)
TypeError: 'str' does not support the buffer interface
```
Is it somewere I wrong?

**Comment by Hubbitus** [comment]
Thank you.
