### ISSUE TITLE
How to select nothing?

### ISSUE THREAD

**Issue by polm** [mooz/percol#79]
Is there a standard way to select nothing in percol? I've been using `ctrl+c` so far but it prints an error and doesn't clean up the screen.

**Comment by mooz** [comment]
`ctrl+c` is a standard way. It ends your percol session without any selection.

What kind of errors did you get?

**Comment by polm** [comment]
This is the error I get:  

    Traceback (most recent call last):
      File "/usr/bin/percol", line 31, in <module>
        main()
      File "/usr/lib/python2.7/site-packages/percol/cli.py", line 284, in main
        exit_code = percol.loop()
      File "/usr/lib/python2.7/site-packages/percol/__init__.py", line 120, in __exit__
        curses.endwin()
    _curses.error: endwin() returned ERR

I'm using 0.1.0 so I guess it's out of date, not sure if that should make a difference though.

**Comment by polm** [comment]
Upgraded to the latest pip version and still getting the error. I'm using Arch Linux, Python2 version is 2.7.10. If there's anything else it'd help to know please tell me.

**Comment by polm** [comment]
Any idea why I'm getting the errors? Am I doing something wrong?

**Comment by clach04** [comment]
This is also an issue with https://github.com/mooz/percol/blob/4b28037e328da3d0fe8165c11b800cbaddcb525e/README.md?plain=1#L196 when used as a library. It looks like a keymap issue (not had chance to play with that yet).

**Comment by clach04** [comment]
Looking at https://github.com/mooz/percol/issues/56 looks like need to map to cancel()
