### ISSUE TITLE
Help debug build error (VersionConflict)

### ISSUE THREAD

**Issue by kaushalmodi** [mooz/percol#92]
Hello,

I have been using percol fine for more than a year now.

Today I just pulled the latest version of percol and tried rebuilding it but it fails with this backtrace
```
/admin-controlled-path/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module email was already imported from /admin-controlled-path/python2.7/email/__init__.pyc, but /admin-controlled-path/python2.7/site-packages is being added to sys.path
  from pkg_resources import Distribution, PathMetadata, ensure_directory
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    install_requires = ["six >= 1.7.3", "cmigemo >= 0.1.5"]
  File "/admin-controlled-path/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/admin-controlled-path/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/admin-controlled-path/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/admin-controlled-path/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/admin-controlled-path/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2029, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/admin-controlled-path/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 592, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (certifi 2016.8.31 (/admin-controlled-path/python2.7/site-packages), Requirement.parse('certifi==2016.8.8'))
```

I do not have `cmigemo` installed (and do not need to). Is the absence of that package causing this problem? The `six` package version is `"1.10.0"`.

Would you be able to help pointing me to the root cause of this error based on the above backtrace?

Thanks.

**Comment by kaushalmodi** [comment]
This was resolved after the admin at work fixed the python 2.7 installation.
